# Generated by Django 5.2 on 2025-04-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
