# Generated by Django 5.2 on 2025-04-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_restaurant_order_restaurant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
