# Generated by Django 5.2 on 2025-04-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_item_cart_item_id_rename_user_cart_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.order'),
        ),
    ]
