# Generated by Django 5.2 on 2025-04-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_address_alter_user_coin_alter_user_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='user',
            new_name='user_id',
        ),
    ]
