# Generated by Django 5.2 on 2025-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_user_restaurant_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='user_id',
            field=models.IntegerField(default=2),
        ),
    ]
