# Generated by Django 5.2 on 2025-04-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_dish_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='item',
        ),
        migrations.AddField(
            model_name='review',
            name='order_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.IntegerField(default=0),
        ),
    ]
