# Generated by Django 5.2 on 2025-04-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_restaurant_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
    ]
