# Generated by Django 5.2.1 on 2025-05-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_item_id_cart_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vnpay_payment_status',
            field=models.CharField(blank=True, choices=[('pending_vnpay', 'VNPAY - Chờ thanh toán'), ('paid_vnpay', 'VNPAY - Đã thanh toán'), ('failed_vnpay', 'VNPAY - Thanh toán lỗi')], db_index=True, help_text='Trạng thái thanh toán cụ thể qua VNPAY.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_response_code',
            field=models.CharField(blank=True, help_text='Mã phản hồi từ VNPAY (vnp_ResponseCode).', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_transaction_no',
            field=models.CharField(blank=True, help_text='Mã giao dịch do VNPAY cung cấp khi thành công (vnp_TransactionNo).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_txn_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Mã giao dịch của Merchant gửi cho VNPAY (vnp_TxnRef).', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(db_index=True, default='Tiền mặt', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.restaurant'),
        ),
    ]
